name: 'sc_interdiction'
version: '1.0.0'
config-version: 2

profile: 'sc_interdiction'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  sc_interdiction:
    +schema: silver

models:
  sc_interdiction:
    staging:
      +materialized: view
      +schema: staging
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: view
      +schema: gold
