sc_interdiction:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      user: "{{ env_var('DBT_USER', 'sc') }}"
      password: "{{ env_var('DBT_PASSWORD', 'sc') }}"
      dbname: "{{ env_var('DBT_DBNAME', 'sc_interdiction') }}"
      schema: raw
      threads: 4
