-- Auto-generated schema from SCLogistics data
-- Generated at compile time by build.rs

CREATE TABLE IF NOT EXISTS locations (
    ref_field TEXT PRIMARY KEY,
    affiliation TEXT,
    block_travel INTEGER,
    callout1 TEXT,
    callout2 TEXT,
    callout3 TEXT,
    density_scale REAL,
    depth REAL,
    description TEXT,
    exclude_from_level_load INTEGER,
    expose_for_player_created_missions INTEGER,
    facing_mode TEXT,
    hide_in_starmap INTEGER,
    hide_in_world INTEGER,
    hide_when_in_adoption_radius INTEGER,
    inner_radius INTEGER,
    is_scannable INTEGER,
    jurisdiction TEXT,
    location_hierarchy_tag TEXT,
    location_image_path TEXT,
    location_medical_image_path TEXT,
    minimum_display_size REAL,
    name TEXT,
    nav_icon TEXT,
    no_auto_body_recovery INTEGER,
    only_show_when_parent_selected INTEGER,
    outer_radius INTEGER,
    override_permanent TEXT,
    override_rotation_speed INTEGER,
    override_rotation_speed_value INTEGER,
    override_show_in_all_zones TEXT,
    parent TEXT,
    respawn_location_type TEXT,
    rotation_speed INTEGER,
    set_entity_location_on_enter INTEGER,
    show_orbit_line INTEGER,
    size REAL,
    size_scale INTEGER,
    star_map_geom_path TEXT,
    star_map_material_path TEXT,
    star_map_shape_path TEXT,
    type_field TEXT,
    use_holo_material INTEGER
);

